# Generated by Django 6.0.2 on 2026-03-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('course_type', models.CharField(choices=[('Training', 'training'), ('Industry Readiness', 'industry readiness')], max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('Student', 'student'), ('Working', 'working'), ('Job Seeker', 'job_seeker')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_mode', models.CharField(choices=[('Online', 'online'), ('Offline', 'offline')], max_length=20)),
                ('preferred_timing', models.CharField(choices=[('Morning', 'morning'), ('Afternoon', 'afternoon'), ('Evening', 'evening')], max_length=50)),
                ('experience_level', models.CharField(choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Experienced', 'experienced')], max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'unique_together': {('email', 'course')},
            },
        ),
    ]
