# Generated by Django 6.0.4 on 2026-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_passwordresettoken_id_alter_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('blog_admin', 'Blog Admin')], max_length=20),
        ),
    ]
