# Generated by Django 6.0.4 on 2026-04-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
