# Generated by Django 6.0.2 on 2026-03-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='section_type',
            field=models.CharField(choices=[('training', 'Training'), ('industry_readiness', 'Industry Readiness')], default='training', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CurriculumSection',
        ),
    ]
