# Generated by Django 6.0.2 on 2026-03-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assignment_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
