# Generated by Django 6.0.2 on 2026-03-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
    ]
