# Generated by Django 6.0.2 on 2026-03-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='max_score',
        ),
    ]
