# Generated by Django 6.0.2 on 2026-03-26 06:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_content_lesson_file_lesson_resource_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='lesson_files/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_upload',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='submissions/'),
        ),
    ]
