# Generated by Django 6.0.2 on 2026-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_file_alter_submission_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted')], default='submitted', max_length=20),
        ),
    ]
