# Generated by Django 6.0.2 on 2026-03-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_submission_score_alter_submission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('lesson', 'student')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
