# Generated by Django 6.0.2 on 2026-03-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='has_assignment',
        ),
    ]
