# Generated by Django 6.0.2 on 2026-03-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_live_class_active',
            field=models.BooleanField(default=False, help_text='Is the live class currently ongoing?'),
        ),
        migrations.AddField(
            model_name='batch',
            name='live_link',
            field=models.URLField(blank=True, help_text='Teams or Zoom link for live class', null=True),
        ),
    ]
