# Generated by Django 6.0.4 on 2026-04-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_lesson_assignment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='assignment_description',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='due_date',
            new_name='assignment_due_date',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='assignment_title',
        ),
    ]
