# Generated by Django 6.0.4 on 2026-04-21 10:56

import courses.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_description_assignment_assignment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_due_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=courses.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, storage=courses.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to='lesson_files/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_upload',
            field=models.FileField(blank=True, null=True, storage=courses.storage.AuthenticatedRawMediaCloudinaryStorage(), upload_to='submissions/'),
        ),
    ]
