# Generated by Django 6.0.2 on 2026-03-23 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(choices=[('Fresher', 'fresher'), ('1-3 Years', '1-3 years'), ('3+ Years', '3+ years')], max_length=20)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('OTHER', 'Other')], default='AADHAAR', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='instructor_docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('assigned_courses', models.ManyToManyField(blank=True, to='courses.course')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
