# Generated by Django 6.0.2 on 2026-03-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='must_change_password',
            new_name='is_first_login',
        ),
    ]
