# Generated by Django 6.0.2 on 2026-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor'),
        ('instructors', '0002_rename_must_change_password_instructor_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='instructor_assigned_courses', to='courses.course'),
        ),
    ]
