# Generated by Django 6.0.2 on 2026-03-26 06:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_alter_instructor_assigned_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='instructor_docs/'),
        ),
    ]
